// Mocks generated by Mockito 5.4.5 from annotations
// in wcas_frontend/test/models/request/file_attachment/document_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:file_picker/file_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:wcas_frontend/core/services/api_service/api_manager.dart'
    as _i2;
import 'package:wcas_frontend/core/services/file_download_service/service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppResponse_0 extends _i1.SmartFake implements _i2.AppResponse {
  _FakeAppResponse_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FileDownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileDownloadService extends _i1.Mock
    implements _i3.FileDownloadService {
  MockFileDownloadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AppResponse> downloadFile(
    String? endpoint,
    String? fileName, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? additionalHeaders = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [endpoint, fileName],
          {
            #queryParams: queryParams,
            #additionalHeaders: additionalHeaders,
          },
        ),
        returnValue: _i4.Future<_i2.AppResponse>.value(
          _FakeAppResponse_0(
            this,
            Invocation.method(
              #downloadFile,
              [endpoint, fileName],
              {
                #queryParams: queryParams,
                #additionalHeaders: additionalHeaders,
              },
            ),
          ),
        ),
      ) as _i4.Future<_i2.AppResponse>);

  @override
  _i4.Future<void> openFileInNewTab(_i5.Uint8List? bytes, String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(#openFileInNewTab, [bytes, fileName]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String fileToBase64(_i6.PlatformFile? file) => (super.noSuchMethod(
        Invocation.method(#fileToBase64, [file]),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(#fileToBase64, [file]),
        ),
      ) as String);
}
