class ReferenceDataKeys {
  static const requestStatus = "REQUEST_STATUS";
  static const requestType = "REQUEST_TYPE";
  static const applicationType = "APPLICATION_TYPE";
  static const transactionType = "TRANSACTION_TYPE";
  static const roleType = "ROLE_TYPE";
  static const auditEntityList = "AUDIT_ENTITY_LIST";
  static const searchCriteria = "SEARCH_CRITERIA";
  static const advanceRequestType = "ADVANCE REQUEST TYPE";
  static const segmentType = "SEGMENT_TYPE";
  static const regionList = "REGION_LIST";
  static const customerType = "FI_CUSTOMER_TYPE";
  static const applicationSegment = "APPLICATION_SEGMENT";
  static const certificateType = "CERTIFICATE_TYPE";
  static const yesNoNa = "YES/NO/NA";
  static const healthCode = "HEALTH_CODE";
  static const advancePurposeCode = "ADVANCE_PURPOSE_CODE";
  static const prupose = "PURPOSE";
  static const sicCodeList = "SIC_CODE_LIST";
  static const tlIssuingAuthorityList = "TL_ISSUING_AUTHORITY_LIST";
  static const cccStatus = "CCC_STATUS";
  static const customerIdentificationList = "CUSTOMER_IDENTIFICATION_LIST";
  static const terminationReason = "TERMINATION_REASON";
  static const esgSectionTitles = "ESG_SECTION_NAME";
  static const excludedActivityList = "EXCLUDED_ACTIVITY_LIST";
  static const esgAdittionalGuidance = "ADDITIONAL_GUIDANCE_INSTRUCTION";
  static const esgSffCategory = "SUSTAINABLE_FINANCE_CATEGORY";
  static const conditionStatus = "CONDITIONS_STATUS";
  static const conditionFrequency = "CONDITIONS_FREQUENCY";
  static const conditionAction = "CONDITIONS_ACTION";
  static const covenantType = "COVENANTS_TYPE";
  static const covenantConditionStatus = "COVENANTS_STATUS";
  static const covenantFrequency = "COVENANTS_FREQUENCY";
  static const covenantConditionAction = "COVENANTS_ACTION";
  static const covenantBasicSeperation = "COVENANTS_BASIS_OF_PREPARATION";
  static const covenantSubmissionTime = "COVENANTS_TIME_FOR_SUBMISSION";
  static const covenantAuditStatus = "COVENANTS_AUDIT_STATUS";
  static const covenantDescriptionTemplate = "COVENANT_DESCRIPTION_TEMPLATE";
  static const covenantDescription = "COVENANTS_DESCRIPTION";
  static const covenantSubtype = "COVENANTS_SUB_TYPE";
  static const covenantPeriod = "COVENANTS_PERIOD";
  static const facilityTypes = "FACILITY_TYPE";
  static const facilityFeeTypes = "FACILITY_FEE_TYPE";
  static const facilityTypesFeeFrequency = "FACILITY_FEE_TYPE_FREQUENCY";
  static const conditionDescriptionTemplate = "CONDITIONS_SUB_TYPE";
  static const sAndP = "SP_RATING";
  static const moodys = "MOODY_RATING";
  static const fitch = "FITCH_RATING";
  static const bankList = "BANK_LIST";
  static const advanceType = "ADVANCE_TYPE";
  static const securityType = "SECURITY_TYPE";
  static const securityStatus = "SECURITY_STATUS";
  static const securityHeldAs = "SECURITY_HELD_AS";
  static const sector = "SECTOR_DESCRIPTION_LIST";
  static const projectType = "PROJECT_TYPE";
  static const contractType = "CONTRACT_TYPE";
  static const regulatorySpecialisedLendingFinanceType =
      "REGULATORY_SPECIALISED_LENDING_FINANCE_TYPE";

  static const limitType = "LIMIT_TYPE";
  static const limitGroup = "LIMIT_GROUP";
  static const limitCapsType = "LIMIT_CAPS_TYPES";
  static const ifrsStaging = "IFRS_STAGING";
  static const policyDeviation = "POLICY_DEVIATIONS";
  static const largeExposureLimit = "LARGE_EXPOSURE_LIMIT";
  static const ownerType = "OWNER_TYPE";
  static const restructuredRescheduled = "RESTRUCTURED_RESCHEDULED";
  static const exposureStrategy = "EXPOSURE_STRATEGY";
  static const productType = "PRODUCT_TYPE";
  static const cancellationReason = "CANCELLATION_REASON";
  static const conditionGeneral = "CONDITIONS_GENERAL_SPECIFIC";
  static const conditionStandard = "CONDITIONS_DESCRIPTION";
  static const covenantConditionType = "CONDITIONS_TYPE";
  static const financialCovenantSubtype = "FINANCIAL_COVENANT_SUBTYPE";
  static const thresholdType = "COVENANTS_THRESHOLD_TYPE";
  static const covenantGeneralSpecific = "COVENANT_GENERAL_SPECIFIC";
  static const borrowerRole = "BORROWER_ROLE";
  static const securityBorrowerRole = "SECURITY_BORROWER ROLE";
  static const financialRatioType = "FINANCIAL_RATIOS_TYPE";
  static const financialCategory = "FINANCIALS_CATEGORY";
  static const financialHealth = "FINANCIALS_HEALTH";
  static const countryRatings = "COUNTRY_RATINGS";
  static const accountType = "ACCOUNT_TYPE";
  static const seniority = "SENIORITY";
  static const sustanabilityClassification = "SUSTAINABILITY_CLASSIFICATION";
  static const period = "PERIOD";
  static const benchMark = "INDEX";
  static const marginSign = "MARGIN_SIGN";
  static const commitmentAccountNumbers = "COMMITMENT_ACCOUNT_NUMBERS";
  static const propertyType = "PROPERTY_TYPE";
  static const propertySubType = "PROPERTY_SUB_TYPE";
  static const currencyAED = "AED";
  static const deferredWaived = "DEFERRED-WAIVED";
  static const securityDeferredWaived = "SECURITY_DEFERRED_WAIVED_BY";
  static const legalStatus = "LEGAL-STATUS";
  static const securityLegalStatus = "SECURITY_PROVIDER_LEGAL_STATUS";
  static const emirates = "EMIRATES";
  static const emiratesItems = "EMIRATE_LIST";

  static const documentTypes = "FA_DOC_TYPE";
  static const fstSubTypes = "FST_SUB_TYPE";
  static const fstSubsubTypes = "FST_SUB_SUB_TYPE";
  static const languages = "LANGUAGE";
  static const clSubTypes = "CL_SUB_TYPE";
  static const cdSubTypes = "CD_SUB_TYPE";
  static const caSubTypes = "CA_SUB_TYPE";
  static const caSubSubTypes = "CA_SUB_SUB_TYPE";
  static const caSubSubSubTypes = "CA_SUB_SUB_SUB_TYPE";

  static const branchList = "BRANCH_LIST";
  static const subSegmentValidation = "SUB_SEGMENT_VALIDATION";
  static const economicZones = "FREE_ZONE";
  static const externalRatingAgencyValues = "EXTERNAL_RATING_AGENCY_VALUES";
}

void testReferenceKeys() {
  ReferenceDataKeys.covenantConditionType;
  ReferenceDataKeys.requestStatus;
  ReferenceDataKeys.requestType;
  ReferenceDataKeys.applicationType;
  ReferenceDataKeys.transactionType;
  ReferenceDataKeys.roleType;
  ReferenceDataKeys.auditEntityList;
  ReferenceDataKeys.searchCriteria;
  ReferenceDataKeys.advanceRequestType;
  ReferenceDataKeys.segmentType;
  ReferenceDataKeys.regionList;
  ReferenceDataKeys.customerType;
  ReferenceDataKeys.applicationSegment;
  ReferenceDataKeys.certificateType;
  ReferenceDataKeys.yesNoNa;
  ReferenceDataKeys.healthCode;
  ReferenceDataKeys.advancePurposeCode;
  ReferenceDataKeys.sicCodeList;
  ReferenceDataKeys.tlIssuingAuthorityList;
  ReferenceDataKeys.cccStatus;
  ReferenceDataKeys.customerIdentificationList;
  ReferenceDataKeys.terminationReason;
  ReferenceDataKeys.esgSectionTitles;
  ReferenceDataKeys.esgAdittionalGuidance;
  ReferenceDataKeys.esgSffCategory;
  ReferenceDataKeys.covenantType;
  ReferenceDataKeys.covenantConditionStatus;
  ReferenceDataKeys.covenantFrequency;
  ReferenceDataKeys.covenantConditionAction;
  ReferenceDataKeys.covenantDescriptionTemplate;
  ReferenceDataKeys.facilityTypes;
  ReferenceDataKeys.covenantSubtype;
  ReferenceDataKeys.covenantPeriod;
  ReferenceDataKeys.covenantBasicSeperation;
  ReferenceDataKeys.covenantSubmissionTime;
  ReferenceDataKeys.covenantAuditStatus;
  ReferenceDataKeys.conditionDescriptionTemplate;
  ReferenceDataKeys.sAndP;
  ReferenceDataKeys.moodys;
  ReferenceDataKeys.fitch;
  ReferenceDataKeys.bankList;
  ReferenceDataKeys.advanceType;
  ReferenceDataKeys.securityType;
  ReferenceDataKeys.securityStatus;
  ReferenceDataKeys.securityHeldAs;
  ReferenceDataKeys.sector;
  ReferenceDataKeys.projectType;
  ReferenceDataKeys.contractType;
  ReferenceDataKeys.regulatorySpecialisedLendingFinanceType;
  ReferenceDataKeys.limitType;
  ReferenceDataKeys.ifrsStaging;
  ReferenceDataKeys.policyDeviation;
  ReferenceDataKeys.restructuredRescheduled;
  ReferenceDataKeys.exposureStrategy;
  ReferenceDataKeys.productType;
  ReferenceDataKeys.cancellationReason;
  ReferenceDataKeys.conditionGeneral;
  ReferenceDataKeys.conditionStandard;
  ReferenceDataKeys.financialCovenantSubtype;
  ReferenceDataKeys.thresholdType;
  ReferenceDataKeys.borrowerRole;
  ReferenceDataKeys.countryRatings;
  ReferenceDataKeys.subSegmentValidation;
}
